blank_issues_enabled: false
contact_links:
  - name: Auth0 Community
    url: https://community.auth0.com
    about: Discuss this SDK in the Auth0 Community forums
  - name: Library Documentation
    url: https://github.com/auth0/omniauth-auth0#documentation
    about: Read the library docs
